// generated file on Sun Apr 15 18:58:01 CEST 2018

var song_list = {
  songs : [
    new SongObject("3 Doors Down", "Here Without You", "-")
   ,new SongObject("3 Doors Down", "When I'm Gone", "-")
   ,new SongObject("30 Seconds to Mars", "The Kill", "-")
   ,new SongObject("A", "ha - Take On Me", "-")
   ,new SongObject("Abba", "Dancing Queen", "-")
   ,new SongObject("Abba", "Money, Money, Money", "-")
   ,new SongObject("ABBA", "Waterloo", "-")
   ,new SongObject("AC", "DC - Highway To Hell", "-")
   ,new SongObject("Ace of Base", "All That She Wants", "-")
   ,new SongObject("Aerosmith", "Dont want to miss a thing", "-")
   ,new SongObject("After Dark", "La Dolce Vita", "-")
   ,new SongObject("After Forever", "Beetween Love And Fire", "-")
   ,new SongObject("After Forever", "Follow In The Cry", "-")
   ,new SongObject("Air Supply", "All Out Of Love", "-")
   ,new SongObject("Alannah Myles", "Black Velvet", "-")
   ,new SongObject("Alcazar", "Not A Sinner Nor A Saint", "-")
   ,new SongObject("Alice Cooper", "No More Mr. Nice Guy", "-")
   ,new SongObject("Alice in Chains", "Would", "-")
   ,new SongObject("Alphaville", "Forever Young", "-")
   ,new SongObject("Alter Bridge", "Metalingus", "-")
   ,new SongObject("America", "The Last Unicorn", "-")
   ,new SongObject("Anastacia", "Left Outside Alone", "-")
   ,new SongObject("Anastacia", "One Day In Your Life", "-")
   ,new SongObject("Anastacia", "Sick and Tired", "-")
   ,new SongObject("Annett Louisan", "Das Spiel", "-")
   ,new SongObject("Annie Lennox", "Sweet Dreams", "-")
   ,new SongObject("Aqua", "Barbie Girl", "-")
   ,new SongObject("Aretha Franklin", "Respect", "-")
   ,new SongObject("Arja Saijonmaa", "Högt Över Havet", "-")
   ,new SongObject("Ashlee Simpson", "Boyfriend", "-")
   ,new SongObject("Ashlee Simpson", "Pieces Of Me", "-")
   ,new SongObject("At Vance", "Eye Of The Tiger", "-")
   ,new SongObject("At Vance", "Money, Money, Money", "-")
   ,new SongObject("Atomic Kitten", "Eternal Flame", "-")
   ,new SongObject("Audioslave", "Cochise", "-")
   ,new SongObject("Avril Lavigne", "Complicated", "-")
   ,new SongObject("Avril Lavigne", "I'm With You", "-")
   ,new SongObject("Avril Lavigne", "My Happy Ending", "-")
   ,new SongObject("Avril Lavigne", "Sk8er Boi", "-")
   ,new SongObject("Azumanga Daioh", "Soramimi Cake", "-")
   ,new SongObject("Azúcar Moreno", "Sólo Se Vive Una Vez", "-")
   ,new SongObject("Backstreet Boys", "I Wan't it that Way", "-")
   ,new SongObject("Bananarama", "I Heard A Rumour", "-")
   ,new SongObject("Bananarama", "Venus", "-")
   ,new SongObject("Barbados", "Världen Utanför", "-")
   ,new SongObject("Barry Manilo", "Mandy", "-")
   ,new SongObject("Barry White", "You're The First, The Last, My Everything", "-")
   ,new SongObject("Beatles", "Yesterday", "-")
   ,new SongObject("Belinda Carlisle", "Heaven Is A Place On Earth", "-")
   ,new SongObject("Beyonce", "Crazy In Love", "-")
   ,new SongObject("Bill Withers", "Ain't No Sunshine", "-")
   ,new SongObject("Billy Joel", "Uptown Girl", "-")
   ,new SongObject("Black Eyed Peas", "Shut Up", "-")
   ,new SongObject("Black Sabbath", "Paranoid", "-")
   ,new SongObject("Blind Guardian", "A Past And Future Secret", "-")
   ,new SongObject("Blind Guardian", "And The Story Ends", "-")
   ,new SongObject("Blind Guardian", "Black Chamber", "-")
   ,new SongObject("Blind Guardian", "Fly", "-")
   ,new SongObject("Blind Guardian", "Mirror Mirror", "-")
   ,new SongObject("Blind Guardian", "Surfin' Usa", "-")
   ,new SongObject("Blind Guardian", "The Bard's Song (In The Forest)", "-")
   ,new SongObject("Blink 182", "I Miss You", "-")
   ,new SongObject("Blondie", "Heart Of Glass", "-")
   ,new SongObject("Blue", "One Love", "-")
   ,new SongObject("Blue Oyster Cult", "(Don't Fear) The Reaper", "-")
   ,new SongObject("Blues Brothers", "Everybody Needs Somebody", "-")
   ,new SongObject("Blur", "Parklife", "-")
   ,new SongObject("Bob Marley & The Wailers", "Redemption Song", "-")
   ,new SongObject("Bob Marley", "Could you be loved [SC]", "-")
   ,new SongObject("Bodo Wartke", "Liebeslied", "-")
   ,new SongObject("Boney M", "Daddy Cool", "-")
   ,new SongObject("Bonnie Tyler", "Total Eclipse of the Heart", "-")
   ,new SongObject("Boston", "More Than A Feeling", "-")
   ,new SongObject("Boy Meets Girl", "Waiting For A Star To Fall", "-")
   ,new SongObject("Brandsta City Släckers", "Kom Och Ta Mig", "-")
   ,new SongObject("Bro'sis", "Do You", "-")
   ,new SongObject("Bruce Dickinson", "Tears Of The Dragon", "-")
   ,new SongObject("Bryan Adams", "Summer of 69", "-")
   ,new SongObject("Bucks Fizz", "Making Your Mind Up", "-")
   ,new SongObject("Buggles", "Video Killed The Radio Star", "-")
   ,new SongObject("Bullet For My Valentine", "All These Things I Hate (revolve Around Me)", "-")
   ,new SongObject("Busted", "Crashed The Wedding", "-")
   ,new SongObject("böhse onkelz", "Auf gute freunde", "-")
   ,new SongObject("böhse onkelz", "Ganz egal", "-")
   ,new SongObject("Böhse Onkelz", "Ich bin in dir", "-")
   ,new SongObject("Böhse Onkelz", "Mexico", "-")
   ,new SongObject("böhse onkelz", "Nur die besten sterben jung", "-")
   ,new SongObject("Böhse Onkelz", "Stunde Des Siegers", "-")
   ,new SongObject("böhse onkelz", "Wir sind immer für euch da", "-")
   ,new SongObject("böhse Onkelz", "zuviel", "-")
   ,new SongObject("Candi Staton", "Young Hearts Run Free", "-")
   ,new SongObject("Carl Douglas", "Kung Fu Fighting", "-")
   ,new SongObject("Carola Häggkvist", "Främling", "-")
   ,new SongObject("Celine Dion", "My Heart Will Go On", "-")
   ,new SongObject("Charlene", "I've Never Been To Me", "-")
   ,new SongObject("Charlotte Church", "Crazy Chick", "-")
   ,new SongObject("Charlotte Nilsson", "Take Me To Your Heaven", "-")
   ,new SongObject("Charlotte Nilsson", "Tusen Och En Natt", "-")
   ,new SongObject("Cheap Trick", "I Want You To Want Me", "-")
   ,new SongObject("Cher", "If I Could Turn Back Time", "-")
   ,new SongObject("Coldplay", "Speed of Sound", "-")
   ,new SongObject("Craig david", "I walking away", "-")
   ,new SongObject("Crash Test Dummies", "MMM MMM MMM", "-")
   ,new SongObject("Crystal King", "Ai wo Torimodose!! (You wa Shock)", "-")
   ,new SongObject("Culture Club", "Do You Really Want To Hurt Me", "-")
   ,new SongObject("Culture Club", "Karma chameleon", "-")
   ,new SongObject("Cutting Crew", "Died In Your Arms", "-")
   ,new SongObject("Cyndi Lauper", "She bop", "-")
   ,new SongObject("Cyndi Lauper", "Time After Time", "-")
   ,new SongObject("Dana Winner", "Moonlight Shadow", "-")
   ,new SongObject("Daniel Bedingfield", "If You're Not The One", "-")
   ,new SongObject("David Bowie", "Changes", "-")
   ,new SongObject("David Bowie", "Life On Mars", "-")
   ,new SongObject("Dead or alive", "You Spin Me Round (Like A Record)", "-")
   ,new SongObject("Dead Smiling Pirates", "I 18", "-")
   ,new SongObject("Deee", "lite - Groove is in the Heart", "-")
   ,new SongObject("Deep Purple", "Smoke On The Water", "-")
   ,new SongObject("Destiny's Child", "Survivor", "-")
   ,new SongObject("Deutschmacher", "Das W auf dem Trikot", "-")
   ,new SongObject("Dexy's Midnight Runners", "Come On Eileen", "-")
   ,new SongObject("Dido", "Thank You", "-")
   ,new SongObject("Dido", "White Flag", "-")
   ,new SongObject("Die Aerzte", "Maenner Sind Schweine", "-")
   ,new SongObject("die aerzte", "nichts in der Welt", "-")
   ,new SongObject("Die Aerzte", "Super Drei", "-")
   ,new SongObject("Die Fantastischen Vier", "Geboren", "-")
   ,new SongObject("Die Prinzen", "Alles Nur Geklaut", "-")
   ,new SongObject("Die Prinzen", "Du musst ein Schwein sein", "-")
   ,new SongObject("Die Ärzte", "Manchmal haben Frauen", "-")
   ,new SongObject("Die Ärzte", "Schrei nach Liebe", "-")
   ,new SongObject("Die Ärzte", "Westerland", "-")
   ,new SongObject("Die Ärzte", "Zu Spät", "-")
   ,new SongObject("Dieter Thomas Kuhn", "Es war Sommer (Die wahre Geschichte)", "-")
   ,new SongObject("Disney", "Gummibären", "-")
   ,new SongObject("Dolly Parton", "9 To 5", "-")
   ,new SongObject("Drafi Deutscher", "Mamor, Stein und Eisen bricht (Movie)", "-")
   ,new SongObject("Duran Duran", "Ordinary World", "-")
   ,new SongObject("Dusty Springfield", "Son of a Preacher Man", "-")
   ,new SongObject("Edguy", "King Of Fools", "-")
   ,new SongObject("Edguy", "Superheroes", "-")
   ,new SongObject("Ella Fitzgerald and Louis Armstrong", "Let's Call The Whole Thing Off", "-")
   ,new SongObject("Elton John & Kiki Dee", "Don't Go Breaking My Heart", "-")
   ,new SongObject("Elton John", "Rocket Man", "-")
   ,new SongObject("Elvis Presley", "Blue Suede Shoes", "-")
   ,new SongObject("Elvis Presley", "Suspicious Minds", "-")
   ,new SongObject("Elvis Presley", "Way Down", "-")
   ,new SongObject("Entwine", "Losing The Ground", "-")
   ,new SongObject("Eric Clapton", "Tears in Heaven (unplugged)", "-")
   ,new SongObject("Europe", "Carrie", "-")
   ,new SongObject("Europe", "The final countdown", "-")
   ,new SongObject("Evanecence", "Bring me to life", "-")
   ,new SongObject("Evanescence", "Going Under", "-")
   ,new SongObject("Evanescence", "My Immortal", "-")
   ,new SongObject("Evanescence", "My Last Breath", "-")
   ,new SongObject("Faith No More", "Easy", "-")
   ,new SongObject("Fall Out Boy", "This Ain't A Scene", "-")
   ,new SongObject("Fame", "Give Me Your Love", "-")
   ,new SongObject("Foo Fighters", "Best Of You", "-")
   ,new SongObject("Foo Fighters", "My Hero", "-")
   ,new SongObject("Fools Garden", "Lemon tree", "-")
   ,new SongObject("Forgeiner", "I Want To Know What Love Is", "-")
   ,new SongObject("Frank Sinatra", "New York, New York", "-")
   ,new SongObject("Free", "Alright Now", "-")
   ,new SongObject("Gamma Ray", "Abyss Of The Void", "-")
   ,new SongObject("Gamma Ray", "Abyss Of The Void (karaoke)", "-")
   ,new SongObject("Geier Sturzflug", "Bruttosozialprodukt", "-")
   ,new SongObject("Genesis", "I Can't dance", "-")
   ,new SongObject("George Michael", "Careless Whisper", "-")
   ,new SongObject("George Michael", "Faith", "-")
   ,new SongObject("Girls Aloud", "Biology", "-")
   ,new SongObject("Gloria Gaynor", "I Am What I Am", "-")
   ,new SongObject("Gloria Gaynor", "I Will Survive", "-")
   ,new SongObject("Good Charlotte", "Girls And Boys", "-")
   ,new SongObject("Good Charlotte", "I Just Wanna Live", "-")
   ,new SongObject("Green Day", "American Idiot", "-")
   ,new SongObject("Green Day", "Wake me up when September ends", "-")
   ,new SongObject("Hammerfall", "Blood Bound", "-")
   ,new SongObject("Hammerfall", "Hearts On Fire", "-")
   ,new SongObject("Hammerfall", "Renegade", "-")
   ,new SongObject("Heart", "Alone", "-")
   ,new SongObject("Helena Paparizou", "My Number One", "-")
   ,new SongObject("Hermes House Band", "Country Roads", "-")
   ,new SongObject("Herreys", "Diggi-Loo Diggi-Ley", "-")
   ,new SongObject("Him", "Join Me", "-")
   ,new SongObject("Hombres G", "Lo Noto", "-")
   ,new SongObject("Hombres G", "No Te Escaparás", "-")
   ,new SongObject("Hoobastank", "The Reason", "-")
   ,new SongObject("Hotel California", "The Eagles", "-")
   ,new SongObject("Hubert Kah", "Sternenhimmel", "-")
   ,new SongObject("Iggy Pop", "Real Wild One", "-")
   ,new SongObject("Iron Maiden", "Fear Of The Dark", "-")
   ,new SongObject("Iron Maiden", "Hallowed Be Thy Name", "-")
   ,new SongObject("Iron Maiden", "The Trooper", "-")
   ,new SongObject("Ixi", "Knutschfleck", "-")
   ,new SongObject("Jackie Wilson", "Reet Petite", "-")
   ,new SongObject("Jamelia", "Stop", "-")
   ,new SongObject("Jamelia", "Superstar", "-")
   ,new SongObject("Jamelia", "Superstar (Demo)", "-")
   ,new SongObject("James Blunt", "Wise Men", "-")
   ,new SongObject("James Blunt", "You're Beautiful", "-")
   ,new SongObject("Jamiroquai", "Deeper Underground", "-")
   ,new SongObject("Jan Johansen", "Se På Mig", "-")
   ,new SongObject("Javine", "Real Things", "-")
   ,new SongObject("Jeden Osiem L", "Jak zapomniec", "-")
   ,new SongObject("Jennifer Lopez", "Jenny From The Block", "-")
   ,new SongObject("Jill Johnson", "Crazy In Love", "-")
   ,new SongObject("Joachim Witt", "Goldener Reiter", "-")
   ,new SongObject("John Lennon", "Imagine", "-")
   ,new SongObject("Johnny Cash", "Ring Of Fire", "-")
   ,new SongObject("Jon Secada", "Just Another Day", "-")
   ,new SongObject("Jonathan Coulton", "A Talk with George", "-")
   ,new SongObject("Jonathan Coulton", "Better", "-")
   ,new SongObject("Jonathan Coulton", "Big Bad World One", "-")
   ,new SongObject("Jonathan Coulton", "Chiron Beta Prime", "-")
   ,new SongObject("Jonathan Coulton", "Code Monkey", "-")
   ,new SongObject("Jonathan Coulton", "Creepy Doll", "-")
   ,new SongObject("Jonathan Coulton", "Dance, Soterios Johnson, Dance", "-")
   ,new SongObject("Jonathan Coulton", "First of May", "-")
   ,new SongObject("Jonathan Coulton", "Flickr [VIDEO]", "-")
   ,new SongObject("Jonathan Coulton", "Furry Old Lobster", "-")
   ,new SongObject("Jonathan Coulton", "I Crush Everything", "-")
   ,new SongObject("Jonathan Coulton", "I Feel Fantastic", "-")
   ,new SongObject("Jonathan Coulton", "I'm Your Moon", "-")
   ,new SongObject("Jonathan Coulton", "Ikea", "-")
   ,new SongObject("Jonathan Coulton", "Monkey Shines", "-")
   ,new SongObject("Jonathan Coulton", "Mr. Fancy Pants", "-")
   ,new SongObject("Jonathan Coulton", "My Beige Bear", "-")
   ,new SongObject("Jonathan Coulton", "Not About You", "-")
   ,new SongObject("Jonathan Coulton", "Re- Your Brains", "-")
   ,new SongObject("Jonathan Coulton", "Shop Vac", "-")
   ,new SongObject("Jonathan Coulton", "Skullcrusher Mountain", "-")
   ,new SongObject("Jonathan Coulton", "That Spells DNA", "-")
   ,new SongObject("Jonathan Coulton", "The Future Soon", "-")
   ,new SongObject("Jonathan Coulton", "When You Go", "-")
   ,new SongObject("Joshua Morin", "On The Run", "-")
   ,new SongObject("Joss Stone", "Super Duper Love", "-")
   ,new SongObject("Judas Priest", "You've Got Another Thing Comin'", "-")
   ,new SongObject("Katharina and the waves", "Walking on Sunshine", "-")
   ,new SongObject("Keane", "Somewhere Only We Know", "-")
   ,new SongObject("Kikki Danielsson", "Bra Vibrationer", "-")
   ,new SongObject("Kikki, Bettan och Lotta", "Vem È Dé Du Vill Ha", "-")
   ,new SongObject("Kim Wilde", "Kids In America", "-")
   ,new SongObject("Kiss", "Nothin' To Lose", "-")
   ,new SongObject("Klaus Lage", "1000 und eine Nacht", "-")
   ,new SongObject("Kylie Minogue", "I Should Be So Lucky", "-")
   ,new SongObject("Kylie Minogue", "In Your Eyes", "-")
   ,new SongObject("L'Arc~en~Ciel", "Blurry Eyes", "-")
   ,new SongObject("La Oreja de Van Gogh", "20 De Enero", "-")
   ,new SongObject("La Oreja de Van Gogh", "Puedes Contar Conmigo", "-")
   ,new SongObject("Lacuna Coil", "Enjoy The Silence", "-")
   ,new SongObject("Laith Al", "Deen - Alles An Dir", "-")
   ,new SongObject("Lasse Holm och Monica Törnell", "É Dé Det Här Du Kallar Kärlek", "-")
   ,new SongObject("Leann Rimes", "Can't Fight The Moonlight", "-")
   ,new SongObject("Lemar", "50-50", "-")
   ,new SongObject("Lena Philipsson", "Dansa I Neon", "-")
   ,new SongObject("Liberty X", "Just A Little", "-")
   ,new SongObject("Lightning Seeds", "Three Lions", "-")
   ,new SongObject("Lily Allen", "Littlest Things", "-")
   ,new SongObject("Limahl", "Never ending story", "-")
   ,new SongObject("Limp Bizkit", "Behind Blue Eyes", "-")
   ,new SongObject("Linda Bengtzing", "Jag Ljuger Så Bra", "-")
   ,new SongObject("Linkin Park", "Breaking The Habit", "-")
   ,new SongObject("Linkin Park", "Numb", "-")
   ,new SongObject("Little Richard", "Tutti Frutti", "-")
   ,new SongObject("Lone Star", "Amazed", "-")
   ,new SongObject("Lordi", "Hard Rock Hallelujah", "-")
   ,new SongObject("Los Rodríguez", "Sin Documentos", "-")
   ,new SongObject("Lotta Engberg", "Fyra Bugg Och en Coca Cola", "-")
   ,new SongObject("Lynyrd Skynyrd", "Sweet Home Alabama", "-")
   ,new SongObject("Madonna", "Hung Up", "-")
   ,new SongObject("Madonna", "La Isla Bonita", "-")
   ,new SongObject("Madonna", "Material Girl", "-")
   ,new SongObject("Madonna", "Papa Don't Preach", "-")
   ,new SongObject("Magnus Uggla", "För Kung Och Fosterland", "-")
   ,new SongObject("Manfred Mann", "Do Wah Diddy Diddy", "-")
   ,new SongObject("Manowar", "Warriors Of The World", "-")
   ,new SongObject("Marc Cohn", "Walking In Memphis", "-")
   ,new SongObject("Marianne Rosenberg", "Er gehoert zu mir", "-")
   ,new SongObject("Marietta", "Fire and Ice", "-")
   ,new SongObject("Marillion", "Kayleigh", "-")
   ,new SongObject("Markoolio Och Linda Bengtzing", "Värsta Schlagern", "-")
   ,new SongObject("Markus", "Ich will Spaß", "-")
   ,new SongObject("Maroon5", "This Love", "-")
   ,new SongObject("Martin Kesici", "Angel of Berlin", "-")
   ,new SongObject("Martin Stenmarck", "Las Vegas", "-")
   ,new SongObject("Marvin Gaye", "I Heard It Through The Grapevine", "-")
   ,new SongObject("Mary Roos", "Pinocchio", "-")
   ,new SongObject("Meatloaf", "I'd Do Anything for Love (But I Won't Do That)", "-")
   ,new SongObject("Metallica & Symphony", "Nothing Else Matters", "-")
   ,new SongObject("Metallica", "Nothing Else Matters", "-")
   ,new SongObject("Metallica", "Sad But True", "-")
   ,new SongObject("Metallica", "The Unforgiven I", "-")
   ,new SongObject("Metallica", "The Unforgiven Ii", "-")
   ,new SongObject("Mis", "Teeq - Scandalous", "-")
   ,new SongObject("Modern Talking", "Cheri Cheri Lady", "-")
   ,new SongObject("Monty Python", "Always look on the bright side of life", "-")
   ,new SongObject("Motörhead", "Ace Of Spades", "-")
   ,new SongObject("Mr Big", "To Be With You", "-")
   ,new SongObject("Mr Mister", "Broken Wings", "-")
   ,new SongObject("Mr Mister", "Kyrie", "-")
   ,new SongObject("Münchner Freiheit", "Ohne dich", "-")
   ,new SongObject("Nanne Grönvall", "Håll Om Mig", "-")
   ,new SongObject("Natasha Bedingfield", "Single", "-")
   ,new SongObject("Natasha Bedingfield", "These Words", "-")
   ,new SongObject("Nena", "99 Red Balloons", "-")
   ,new SongObject("Nena", "Irgendwie Irgendwo Irgendwann", "-")
   ,new SongObject("Nick Borgen", "We Are All The Winners", "-")
   ,new SongObject("Nickelback", "How You Remind Me", "-")
   ,new SongObject("Nickelback", "Savin' Me", "-")
   ,new SongObject("Nightwish", "Dead Gardens", "-")
   ,new SongObject("Nightwish", "Fantasmic", "-")
   ,new SongObject("Nightwish", "Phantom Of The Opera", "-")
   ,new SongObject("Nightwish", "Sleeping Sun", "-")
   ,new SongObject("Nightwish", "The Kinslayer", "-")
   ,new SongObject("Nightwish", "Wanderlust", "-")
   ,new SongObject("Nightwish", "Wish I Had An Angel", "-")
   ,new SongObject("Nightwish", "Wishmaster", "-")
   ,new SongObject("Nilsson", "Without You", "-")
   ,new SongObject("Nino de Angelo", "Jenseits von Eden", "-")
   ,new SongObject("Nirvana", "Come As You Are", "-")
   ,new SongObject("Nirvana", "Rape Me", "-")
   ,new SongObject("Nocturnal Rites", "Ring Of Steel", "-")
   ,new SongObject("Norah Jones", "Don't Know Why", "-")
   ,new SongObject("Oasis", "Stop Crying Your Heart Out", "-")
   ,new SongObject("Oasis", "Wonderwall", "-")
   ,new SongObject("Onegai! Teacher", "Shooting Star", "-")
   ,new SongObject("Opus", "Life is Life", "-")
   ,new SongObject("Orson", "Bright Idea", "-")
   ,new SongObject("Outcast", "Roses", "-")
   ,new SongObject("Patrick Nuo", "5 Days", "-")
   ,new SongObject("Patsy Cline", "Crazy", "-")
   ,new SongObject("Paul Anka", "Stand By Me", "-")
   ,new SongObject("Pearl Jam", "Alive", "-")
   ,new SongObject("Pet Shop Boys", "Always On My Mind", "-")
   ,new SongObject("Pet Shop Boys", "Go West", "-")
   ,new SongObject("Peter Gabriel & Kate Bush", "Let It Be", "-")
   ,new SongObject("Petula Clark", "Downtown", "-")
   ,new SongObject("Pornophonique", "Space Invaders", "-")
   ,new SongObject("Pornophonique", "Space Invaders (Kar)", "-")
   ,new SongObject("Prince", "Kiss", "-")
   ,new SongObject("Prince", "When Doves Cry", "-")
   ,new SongObject("Queen", "Another One Bites The Dust", "-")
   ,new SongObject("Queen", "Bicycle Race", "-")
   ,new SongObject("Queen", "Bohemian Rhapsody", "-")
   ,new SongObject("Queen", "Breakthru", "-")
   ,new SongObject("Queen", "Crazy Little Thing Called Love", "-")
   ,new SongObject("Queen", "Don't Stop Me Now", "-")
   ,new SongObject("Queen", "Fat Bottomed Girls", "-")
   ,new SongObject("Queen", "I Want It All", "-")
   ,new SongObject("Queen", "I Want To Break Free", "-")
   ,new SongObject("Queen", "Innuendo", "-")
   ,new SongObject("Queen", "One Vision", "-")
   ,new SongObject("Queen", "Play The Game", "-")
   ,new SongObject("Queen", "Radio Gaga", "-")
   ,new SongObject("Queen", "Somebody To Love", "-")
   ,new SongObject("Queen", "The Show Must Go On", "-")
   ,new SongObject("Queen", "These Are The Days Of Our Lives", "-")
   ,new SongObject("Queen", "Tie Your Mother Down", "-")
   ,new SongObject("Queen", "Under Pressure", "-")
   ,new SongObject("Queen", "Under Pressure [VIDEO]", "-")
   ,new SongObject("Queen", "We Are The Champions", "-")
   ,new SongObject("Queen", "We Are The Champions [VIDEO]", "-")
   ,new SongObject("Queen", "We Will Rock You", "-")
   ,new SongObject("Queen", "We Will Rock You [VIDEO]", "-")
   ,new SongObject("Queen", "Who Wants To Live Forever", "-")
   ,new SongObject("Queen", "Who Wants To Live Forever [VIDEO]", "-")
   ,new SongObject("Queen", "You're My Best Friend", "-")
   ,new SongObject("Queen", "You're My Best Friend [VIDEO]", "-")
   ,new SongObject("Queens Of The Stone Age", "Go With The Flow", "-")
   ,new SongObject("Quiet Riot", "Cum On Feel The Noize", "-")
   ,new SongObject("R Kelly", "I Believe I Can Fly", "-")
   ,new SongObject("Radiohead", "Creep", "-")
   ,new SongObject("Rammstein", "Engel", "-")
   ,new SongObject("Rammstein", "Engel (english Version)", "-")
   ,new SongObject("Rammstein", "Mutter", "-")
   ,new SongObject("Rammstein", "Nebel", "-")
   ,new SongObject("Ramones", "Blitzkrieg Bop", "-")
   ,new SongObject("Reamonn", "Supergirl", "-")
   ,new SongObject("Red Hot Chili Pepper", "Under The Bridge", "-")
   ,new SongObject("Rednex", "Cotton Eye Joe", "-")
   ,new SongObject("Rhapsody", "Dawn Of Victory", "-")
   ,new SongObject("Rhapsody", "The Magic Of The Wizard's Dreams", "-")
   ,new SongObject("Rick Astley", "Never Gonna Give You Up", "-")
   ,new SongObject("Ricky Martin", "Livin' La Vida Loca", "-")
   ,new SongObject("Robbie Williams & Kylie Minogue", "Kids", "-")
   ,new SongObject("Robbie Williams", "Advertising Space", "-")
   ,new SongObject("Robbie Williams", "Let Me Entertain you", "-")
   ,new SongObject("Rockapella", "Sexual Healing", "-")
   ,new SongObject("Rocky Horror Show", "Time Warp", "-")
   ,new SongObject("Ronan Keating", "If Tomorrow Never Comes", "-")
   ,new SongObject("Ronan Keating feat. Yusuf Islam", "Father and Son", "-")
   ,new SongObject("Rosario", "Mi Gato", "-")
   ,new SongObject("Rosenstolz", "Willkommen", "-")
   ,new SongObject("Roxette", "It Must Have Been Love", "-")
   ,new SongObject("Roxette", "Listen To Your Heart", "-")
   ,new SongObject("Roxy Music", "Love Is The Drug", "-")
   ,new SongObject("Roy Orbison", "Pretty Woman", "-")
   ,new SongObject("S Club 7", "Don't Stop Movin'", "-")
   ,new SongObject("Sam Cooke", "Wonderful World", "-")
   ,new SongObject("Sarah Connor", "Living to love you", "-")
   ,new SongObject("Sarah Dawn Finer", "I Remember Love", "-")
   ,new SongObject("Scissor Sisters", "I Don't Feel Like Dancin'", "-")
   ,new SongObject("Scissor Sisters", "Laura", "-")
   ,new SongObject("Scorpions", "Wind of Change", "-")
   ,new SongObject("Scott McKenzie", "San Francisco", "-")
   ,new SongObject("Shakira", "Suerte", "-")
   ,new SongObject("Shakira", "Whenever Wherever", "-")
   ,new SongObject("Shearer", "69", "-")
   ,new SongObject("Shearer", "69 (Kar)", "-")
   ,new SongObject("Shearer", "Can't stop it", "-")
   ,new SongObject("Shearer", "Can't stop it (Kar)", "-")
   ,new SongObject("Shearer", "In My Hand", "-")
   ,new SongObject("Shearer", "Man Song", "-")
   ,new SongObject("Shearer", "Man Song (Kar)", "-")
   ,new SongObject("Shearer", "Stay with me", "-")
   ,new SongObject("Shearer", "Stay with me (Kar)", "-")
   ,new SongObject("Simple Minds", "Don't You Forget About Me", "-")
   ,new SongObject("Sister Sledge", "We are Family", "-")
   ,new SongObject("Smash Mouth", "All Star", "-")
   ,new SongObject("Soft Cell", "Tainted Love", "-")
   ,new SongObject("Sophie Ellis Bextor", "Murder on the Dancefloor", "-")
   ,new SongObject("Spandau Ballet", "Gold", "-")
   ,new SongObject("Spice Girls", "Who do you think you are", "-")
   ,new SongObject("Spider Murphy Hang", "Skandal Im Sperrbezirk", "-")
   ,new SongObject("Starship", "Nothing's Gonna Stop Us Now", "-")
   ,new SongObject("Steppenwolf", "Born To Be Wild", "-")
   ,new SongObject("Steps", "Deeper Shade Of Blue", "-")
   ,new SongObject("Steven Dunston", "Northern Star", "-")
   ,new SongObject("Stevie Wonder", "I just called to say I love you", "-")
   ,new SongObject("Stone Temple Pilots", "Vasoline", "-")
   ,new SongObject("Sublime", "Santeria", "-")
   ,new SongObject("Subway To Sally", "Kleid Aus Rosen", "-")
   ,new SongObject("Sugababes", "Round Round", "-")
   ,new SongObject("Sugababes", "Too Lost In You", "-")
   ,new SongObject("System Of A Down", "Byob Uncut!", "-")
   ,new SongObject("System Of A Down", "Chop Suey", "-")
   ,new SongObject("System Of A Down", "Hypnotize", "-")
   ,new SongObject("System Of A Down", "Lonely Day", "-")
   ,new SongObject("T'Pau", "China In Your Hand", "-")
   ,new SongObject("Take That", "Back for god", "-")
   ,new SongObject("Take That feat. Lulu", "Relight My fire", "-")
   ,new SongObject("Talking Heads", "Burning Down The House", "-")
   ,new SongObject("Tears for Fears", "Everybody Wants To Rule The World", "-")
   ,new SongObject("The Ark", "The Worrying Kind", "-")
   ,new SongObject("The Calling", "Wherever You Will Go", "-")
   ,new SongObject("The Clash", "Should I stay or should I go", "-")
   ,new SongObject("The Corrs", "The Right Time", "-")
   ,new SongObject("The Dandy Warhols", "Bohemian Like You", "-")
   ,new SongObject("The Darkness", "I Believe In a Thing Called Love", "-")
   ,new SongObject("The Foundations", "Build Me Up Buttercup", "-")
   ,new SongObject("The Jackson 5", "I Want You Back", "-")
   ,new SongObject("The Killers", "Mr. Brightside", "-")
   ,new SongObject("The Killers", "When You Were Young", "-")
   ,new SongObject("The Kinks", "Lola", "-")
   ,new SongObject("The mamas and the papas", "We had joy we had fun", "-")
   ,new SongObject("The Monkees", "Daydream Believer", "-")
   ,new SongObject("The Platters", "Only You", "-")
   ,new SongObject("The Police", "Every Breath You Take", "-")
   ,new SongObject("The Police", "Roxanne", "-")
   ,new SongObject("The Poodles", "Night Of Passion", "-")
   ,new SongObject("The Prodigy", "No Good (Start the Dance)", "-")
   ,new SongObject("The Righteous Brothers", "Unchained Melody", "-")
   ,new SongObject("The Rolling Stones", "Sympathy For The Devil", "-")
   ,new SongObject("The Smiths", "This Charming Man", "-")
   ,new SongObject("The Temptations", "My Girl", "-")
   ,new SongObject("The Village People", "YMCA", "-")
   ,new SongObject("Tina Arena", "Chains", "-")
   ,new SongObject("Tina Turner", "Best", "-")
   ,new SongObject("Tina Turner", "What's Love Got To Do With It", "-")
   ,new SongObject("Tokio Hotel", "Durch den Monsun", "-")
   ,new SongObject("Torfrock", "Beinhart", "-")
   ,new SongObject("Toto", "Africa", "-")
   ,new SongObject("Twisted Sister", "We're Not Gonna Take It", "-")
   ,new SongObject("U2", "Beautiful Day", "-")
   ,new SongObject("U2", "I Still Haven't Found What I'm Looking For", "-")
   ,new SongObject("U2", "Vertigo", "-")
   ,new SongObject("U2", "With Or Without You", "-")
   ,new SongObject("Ultra Nate", "Free", "-")
   ,new SongObject("Village People", "Y.M.C.A", "-")
   ,new SongObject("Weather Girls", "It's raining men", "-")
   ,new SongObject("Weird Al Yankovic", "On Ebay", "-")
   ,new SongObject("Westernhagen", "Sexy", "-")
   ,new SongObject("Westlife", "World Of Our Own", "-")
   ,new SongObject("Wham!", "Last Christmas", "-")
   ,new SongObject("Wham!", "Wake me up before you go go", "-")
   ,new SongObject("Whitesnake", "Here I go again", "-")
   ,new SongObject("Whitney Houston", "Greatest Love Of All", "-")
   ,new SongObject("Whitney Houston", "I Wanna Dance With Somebody", "-")
   ,new SongObject("Whitney Houston", "One moment in time", "-")
   ,new SongObject("Wir sind Helden", "Denkmal", "-")
   ,new SongObject("Wise Guys", "Lebendig und kräftig und schärfer", "-")
   ,new SongObject("Wise Guys", "Mensch, wo bist du", "-")
   ,new SongObject("Wise Guys", "Mensch, wo bist du (Kar)", "-")
   ,new SongObject("Within Tempation", "Stand My Ground", "-")
   ,new SongObject("Wolfgang Petry", "Wahnsinn", "-")
   ,new SongObject("Yeah Yeah Yeahs", "Gold Lion", "-")
   ,new SongObject("Yes", "Owner Of A Lonely Heart", "-")
   ,new SongObject("ZZ Top", "Gimme All Your Lovin", "-")
   ,new SongObject("AC", "DC - Back in Black", "-")
   ,new SongObject("AC", "DC - Highway To Hell", "-")
   ,new SongObject("AC", "DC - T.N.T", "-")
   ,new SongObject("AC", "DC - You shook me all night long", "-")
   ,new SongObject("Adele", "Hello", "-")
   ,new SongObject("Adele", "Rolling in the Deep", "-")
   ,new SongObject("Adele", "Someone Like You", "-")
   ,new SongObject("Aerosmith", "Amazing", "-")
   ,new SongObject("Aerosmith", "Crazy", "-")
   ,new SongObject("Aerosmith", "Cryin'", "-")
   ,new SongObject("Alanis Morissette", "Ironic", "-")
   ,new SongObject("Alejandro Sanz", "Corazon partio", "-")
   ,new SongObject("Alice Cooper", "Poison", "-")
   ,new SongObject("Alice in Chains", "Man in the Box", "-")
   ,new SongObject("Alicia Keys", "Fallin'", "-")
   ,new SongObject("Amy Winehouse & Mark Ronson", "Valerie", "-")
   ,new SongObject("Amy Winehouse", "Back To Black", "-")
   ,new SongObject("Amy Winehouse", "Rehab", "-")
   ,new SongObject("Amy Winehouse", "You Know I’m No Good", "-")
   ,new SongObject("Antonio Banderas", "Cancion del Mariachi", "-")
   ,new SongObject("Aqua", "Barbie Girl", "-")
   ,new SongObject("Aventura", "Obsesion", "-")
   ,new SongObject("Belinda Carlisle", "Leave A Light On", "-")
   ,new SongObject("Beyoncé", "If I Were A Boy", "-")
   ,new SongObject("Beyoncé", "Single ladies (Put a ring on it)", "-")
   ,new SongObject("Bill Medley & Jennifer Warnes", "I’ve Had The Time Of My Life", "-")
   ,new SongObject("Blind Melon", "No Rain", "-")
   ,new SongObject("Bloodhound Gang", "Fire Water Burn", "-")
   ,new SongObject("Blue Oyster Cult", "(Don't Fear) The Reaper", "-")
   ,new SongObject("Blur", "Song 2", "-")
   ,new SongObject("Bon Jovi", "Always", "-")
   ,new SongObject("Bon Jovi", "It’s My Life", "-")
   ,new SongObject("Bon Jovi", "Livin' on a prayer", "-")
   ,new SongObject("Bonnie Tyler", "Holding Out For A Hero", "-")
   ,new SongObject("Britney Spears", "Baby One More Time", "-")
   ,new SongObject("Bruce Sprinsteen", "Dancing in the Dark", "-")
   ,new SongObject("Bruno Mars", "Grenade", "-")
   ,new SongObject("Bruno Mars", "Just The Way You Are", "-")
   ,new SongObject("Cardigans", "Erase and Rewind", "-")
   ,new SongObject("Cardigans", "Lovefool", "-")
   ,new SongObject("Cardigans", "My Favourite Game", "-")
   ,new SongObject("Carlos Vives", "La gota fría", "-")
   ,new SongObject("Cheb Khaled", "Aïcha", "-")
   ,new SongObject("Chesney Hawkes", "The One And Only", "-")
   ,new SongObject("Choirboys", "Run To Paradise", "-")
   ,new SongObject("Christina Aguilera", "Genie In A Bottle", "-")
   ,new SongObject("Coldplay", "The Scientist", "-")
   ,new SongObject("Coldplay", "Viva La Vida", "-")
   ,new SongObject("Coldplay", "Yellow", "-")
   ,new SongObject("Common Linnets", "Calm After The Storm", "-")
   ,new SongObject("Conchita Wurst", "Rise Like A Phoenix", "-")
   ,new SongObject("Cosmo Jarvis", "Gay Pirates", "-")
   ,new SongObject("Cranberries", "Zombie", "-")
   ,new SongObject("Crash Test Dummies", "MMM MMM MMM MMM MMM", "-")
   ,new SongObject("Cyndi Lauper", "Girls Just Wanna Have Fun", "-")
   ,new SongObject("Cyndi Lauper", "I Drove All Night", "-")
   ,new SongObject("Cyndi Lauper", "True Colors", "-")
   ,new SongObject("Daddy Yankee", "Llamado de emergencia", "-")
   ,new SongObject("Daddy Yankee", "Lo Que Paso, Paso", "-")
   ,new SongObject("David Hasselhoff", "Looking for Freedom", "-")
   ,new SongObject("Deee", "lite - Groove is in the Heart", "-")
   ,new SongObject("Deep Purple", "Smoke On The Water", "-")
   ,new SongObject("Depeche Mode", "Enjoy The Silence", "-")
   ,new SongObject("Depeche Mode", "It's No Good", "-")
   ,new SongObject("Destiny's Child", "Say My Name", "-")
   ,new SongObject("Destiny's Child", "Survivor", "-")
   ,new SongObject("Die Toten Hosen", "1000 gute Gründe", "-")
   ,new SongObject("Die Toten Hosen", "All die ganzen Jahre", "-")
   ,new SongObject("Die Toten Hosen", "Alles Aus Liebe", "-")
   ,new SongObject("Die Toten Hosen", "Alles Was War", "-")
   ,new SongObject("Die Toten Hosen", "Alles Wird Vorübergehen", "-")
   ,new SongObject("Die Toten Hosen", "Auld lang Syne", "-")
   ,new SongObject("Die Toten Hosen", "Bayern", "-")
   ,new SongObject("Die Toten Hosen", "Bonnie & Clyde", "-")
   ,new SongObject("Die Toten Hosen", "Eisgekühlter Bommerlunder", "-")
   ,new SongObject("Die Toten Hosen", "Freunde", "-")
   ,new SongObject("Die Toten Hosen", "Friss oder Stirb", "-")
   ,new SongObject("Die Toten Hosen", "Hier kommt Alex", "-")
   ,new SongObject("Die Toten Hosen", "Hier Kommt Alex (Unplugged)", "-")
   ,new SongObject("Die Toten Hosen", "Ich bin die Sehnsucht in Dir", "-")
   ,new SongObject("Die Toten Hosen", "Kein Alkohol (ist auch keine Lösung)", "-")
   ,new SongObject("Die Toten Hosen", "Nur zu Besuch", "-")
   ,new SongObject("Die Toten Hosen", "Paradies", "-")
   ,new SongObject("Die Toten Hosen", "Pushed Again", "-")
   ,new SongObject("Die Toten Hosen", "Schön sein", "-")
   ,new SongObject("Die Toten Hosen", "Steh auf, wenn du am Boden bist", "-")
   ,new SongObject("Die Toten Hosen", "Still, Still, Still", "-")
   ,new SongObject("Die Toten Hosen", "Tage Wie Diese", "-")
   ,new SongObject("Die Toten Hosen", "Walkampf", "-")
   ,new SongObject("Die Toten Hosen", "Warum werde ich nicht satt", "-")
   ,new SongObject("Die Toten Hosen", "Was zählt", "-")
   ,new SongObject("Die Toten Hosen", "Wünsch DIR was", "-")
   ,new SongObject("Die Toten Hosen", "Zehn Kleine Jägermeister", "-")
   ,new SongObject("Dixie Chicks", "Not Ready To Make Nice", "-")
   ,new SongObject("DJ Ötzi & Nik P.", "Ein Stern (Der Deinen Namen Trägt)", "-")
   ,new SongObject("DJ Ötzi", "Sweet Caroline", "-")
   ,new SongObject("Don Omar feat. Lucenzo", "Danza Kuduro", "-")
   ,new SongObject("Duffy", "Mercy", "-")
   ,new SongObject("Ed Sheeran", "Galway Girl", "-")
   ,new SongObject("Ed Sheeran", "Give Me Love", "-")
   ,new SongObject("Ed Sheeran", "Lego House", "-")
   ,new SongObject("Ed Sheeran", "The A Team", "-")
   ,new SongObject("Ed Sheeran", "Thinking Out Loud", "-")
   ,new SongObject("Ella Baila Sola", "Cuando los sapos bailen flamenco", "-")
   ,new SongObject("Ella Baila Sola", "Lo echamos a suertes", "-")
   ,new SongObject("Ellie Goulding", "Burn", "-")
   ,new SongObject("Eminem & Rihanna", "Love The Way You Lie", "-")
   ,new SongObject("Enrique Iglesias", "Bailamos", "-")
   ,new SongObject("Enrique Iglesias", "Bailando", "-")
   ,new SongObject("Enrique Iglesias", "Hero", "-")
   ,new SongObject("Enrique Iglesias feat. Pitbull", "I Like It", "-")
   ,new SongObject("Enrique Iglesias y Juan Luis Guerra", "Cuando me enamoro", "-")
   ,new SongObject("Erasure", "Always", "-")
   ,new SongObject("Eros Ramazzotti", "Otra como tú", "-")
   ,new SongObject("Florence + the Machine", "Dog Days Are Over", "-")
   ,new SongObject("Foo Fighters", "Everlong", "-")
   ,new SongObject("Frank Sinatra", "I’ve Got You Under My Skin", "-")
   ,new SongObject("Frank Sinatra", "Let It Snow!", "-")
   ,new SongObject("Frank Sinatra", "My Way", "-")
   ,new SongObject("Garbage", "I Think I'm Paranoid", "-")
   ,new SongObject("Garbage", "Push It", "-")
   ,new SongObject("George Ezra", "Budapest", "-")
   ,new SongObject("Gipsy Kings", "Bamboleo", "-")
   ,new SongObject("Gipsy Kings", "Volare", "-")
   ,new SongObject("Gloria Estefan", "Hoy", "-")
   ,new SongObject("Gloria Estefan", "Wrapped", "-")
   ,new SongObject("Gossip", "Heavy Cross", "-")
   ,new SongObject("Grease", "Summer Nights", "-")
   ,new SongObject("Green Day", "Basket Case", "-")
   ,new SongObject("Green Day", "Brain Stew", "-")
   ,new SongObject("Green Day", "Hitchin a Ride", "-")
   ,new SongObject("Green Day", "When I Come Around", "-")
   ,new SongObject("Guns N' Roses", "Paradise City", "-")
   ,new SongObject("Guns N' Roses", "Sweet Child O' Mine", "-")
   ,new SongObject("Gwen Stefani", "Cool", "-")
   ,new SongObject("Gwen Stefani feat. Akon", "The Sweet Escape", "-")
   ,new SongObject("Helene Fischer", "Atemlos durch die Nacht", "-")
   ,new SongObject("Heroes Del Silencio", "Entre Dos Tierras", "-")
   ,new SongObject("Hole", "Celebrity Skin", "-")
   ,new SongObject("Irene Cara", "Flashdance (What A Feeling)", "-")
   ,new SongObject("James Bay", "Hold Back The River", "-")
   ,new SongObject("James Morrison", "I Won’t Let You Go", "-")
   ,new SongObject("James Morrison", "You Give Me Something", "-")
   ,new SongObject("James Morrison ft. Nelly Furtado", "Broken Strings", "-")
   ,new SongObject("Jewel", "Foolish Games", "-")
   ,new SongObject("Jimmy Barnes", "Working Class Man", "-")
   ,new SongObject("Joan Jett & The Blackhearts", "I love Rock`n´Roll", "-")
   ,new SongObject("John Denver", "Take Me Home Country Roads", "-")
   ,new SongObject("John Lennon", "Imagine", "-")
   ,new SongObject("Johnny Cash", "I Walk The Line", "-")
   ,new SongObject("Johnny Cash", "Ring Of Fire", "-")
   ,new SongObject("Juan Luis Guerra", "El Niágara en bicicleta", "-")
   ,new SongObject("Juan Luis Guerra", "La bilirrubina", "-")
   ,new SongObject("Juan Luis Guerra", "Ojalá que llueva café", "-")
   ,new SongObject("Juan Luis Guerra ft. Juanes", "La calle", "-")
   ,new SongObject("Juan Luis Guerra y 4.40", "Burbujas de amor", "-")
   ,new SongObject("Juan Luis Guerra y Romeo Santos", "Frío, frío", "-")
   ,new SongObject("Juanes", "A Dios Le Pido", "-")
   ,new SongObject("Juanes", "La Camisa Negra", "-")
   ,new SongObject("Katy Perry", "Hot ’n’ Cold", "-")
   ,new SongObject("Katy Perry", "I Kissed A Girl", "-")
   ,new SongObject("Kenny Loggins", "Footloose", "-")
   ,new SongObject("Kenny Rogers", "The Gambler", "-")
   ,new SongObject("Kings Of Leon", "Sex on Fire", "-")
   ,new SongObject("Kings Of Leon", "Use Somebody", "-")
   ,new SongObject("Korn", "Did My Time", "-")
   ,new SongObject("Korn", "Freak On A Leash", "-")
   ,new SongObject("Led Zeppelin", "Stairway to Heaven", "-")
   ,new SongObject("Lenny Kravitz", "Are You Gonna Go My Way", "-")
   ,new SongObject("Leona Lewis", "Run", "-")
   ,new SongObject("Lily Allen", "Fuck You", "-")
   ,new SongObject("Lily Allen", "LDN", "-")
   ,new SongObject("Lily Allen", "Not Fair", "-")
   ,new SongObject("Lily Allen", "Smile", "-")
   ,new SongObject("Lily Allen", "The Fear", "-")
   ,new SongObject("Linkin Park", "In The End", "-")
   ,new SongObject("Lorde", "Royals", "-")
   ,new SongObject("Luis Fonsi feat. Daddy Yankee", "Despacito", "-")
   ,new SongObject("Lynyrd Skynyrd", "Sweet Home Alabama", "-")
   ,new SongObject("Madonna", "Like a Virgin", "-")
   ,new SongObject("Maná y Juan Luís Guerra", "Bendita tu luz", "-")
   ,new SongObject("Marilyn Manson", "Tainted Love", "-")
   ,new SongObject("Mecano", "Hijo de la Luna", "-")
   ,new SongObject("Metallica", "Enter Sandman", "-")
   ,new SongObject("Metallica", "Sad But True", "-")
   ,new SongObject("Michael Jackson", "Bad", "-")
   ,new SongObject("Michael Jackson", "Beat It", "-")
   ,new SongObject("Michael Jackson", "Billie Jean", "-")
   ,new SongObject("Michael Jackson", "Black or White", "-")
   ,new SongObject("Michael Jackson", "Man in the Mirror", "-")
   ,new SongObject("Michael Jackson", "Thriller", "-")
   ,new SongObject("Michael Sembello", "Maniac (Flashdance)", "-")
   ,new SongObject("Miguel Bosé", "Amante bandido", "-")
   ,new SongObject("Mumford & Sons", "I Will Wait", "-")
   ,new SongObject("Mumford & Sons", "Little Lion Man", "-")
   ,new SongObject("Mumford & Sons", "The Cave", "-")
   ,new SongObject("Nelly Furtado", "I'm Like A Bird", "-")
   ,new SongObject("Nickelback", "How You Remind Me", "-")
   ,new SongObject("Nicky Jam & Enrique Iglesias", "El Perdón", "-")
   ,new SongObject("Nine Inch Nails", "Closer", "-")
   ,new SongObject("Nine Inch Nails", "The Perfect Drug", "-")
   ,new SongObject("Nirvana", "About A Girl", "-")
   ,new SongObject("Nirvana", "Come As You Are", "-")
   ,new SongObject("Nirvana", "Heart-Shaped Box", "-")
   ,new SongObject("Nirvana", "In Bloom", "-")
   ,new SongObject("Nirvana", "Lithium", "-")
   ,new SongObject("Nirvana", "Smells Like Teen Spirit", "-")
   ,new SongObject("No Doubt", "Don't Speak", "-")
   ,new SongObject("No Doubt", "Just A Girl", "-")
   ,new SongObject("No Doubt", "Spiderwebs", "-")
   ,new SongObject("No Doubt", "Sunday Morning", "-")
   ,new SongObject("Offspring", "Gone Away", "-")
   ,new SongObject("Offspring", "Self Esteem", "-")
   ,new SongObject("Offspring", "The Kids Aren't Alright", "-")
   ,new SongObject("Offspring", "Why Don't You Get a Job", "-")
   ,new SongObject("Outkast", "Hey Ya", "-")
   ,new SongObject("P!nk", "Raise Your Glass", "-")
   ,new SongObject("P!nk", "Sober", "-")
   ,new SongObject("P!nk", "Try", "-")
   ,new SongObject("P!nk", "U & Ur Hand", "-")
   ,new SongObject("P!nk ft. Lily Allen", "True Love", "-")
   ,new SongObject("P!nk ft. Nate Ruess", "Just Give Me A Reason", "-")
   ,new SongObject("Papa Roach", "Last Resort", "-")
   ,new SongObject("Passenger", "Let Her Go", "-")
   ,new SongObject("Paul McCartney & Michael Jackson", "Say Say Say", "-")
   ,new SongObject("Pearl Jam", "Alive", "-")
   ,new SongObject("Pearl Jam", "Even Flow", "-")
   ,new SongObject("Pearl Jam", "Jeremy", "-")
   ,new SongObject("Pitbull", "I Know You Want Me (Calle Ocho)", "-")
   ,new SongObject("Pitbull feat. Marc Anthony", "Rain Over Me", "-")
   ,new SongObject("Police", "Every Breath You Take", "-")
   ,new SongObject("Police", "Roxanne", "-")
   ,new SongObject("Pulp", "Common People", "-")
   ,new SongObject("Queen", "Bohemian Rhapsody", "-")
   ,new SongObject("Queen", "We Are The Champions", "-")
   ,new SongObject("Queen", "We Will Rock You", "-")
   ,new SongObject("R.E.M.", "Losing My Religion", "-")
   ,new SongObject("R.E.M.", "Man On the Moon", "-")
   ,new SongObject("Radiohead", "Creep", "-")
   ,new SongObject("Red Hot Chili Peppers", "Soul to Squeeze", "-")
   ,new SongObject("Red Hot Chili Peppers", "Under the Bridge", "-")
   ,new SongObject("Rihanna & Justin Timberlake", "Rehab", "-")
   ,new SongObject("Rihanna", "Take A Bow", "-")
   ,new SongObject("Rihanna feat. Mikky Ekko", "Stay", "-")
   ,new SongObject("Rob Zombie", "Dragula Remix", "-")
   ,new SongObject("Santana feat. Maná", "Corazon espinado", "-")
   ,new SongObject("Sarah McLachlan", "Angel", "-")
   ,new SongObject("Shakira", "Ciega, Sordomuda", "-")
   ,new SongObject("Shakira", "Estoy aquí", "-")
   ,new SongObject("Shakira", "Ojos asi", "-")
   ,new SongObject("Shakira", "Waka Waka (This Time for Africa)", "-")
   ,new SongObject("Shakira y Alejandro Sanz", "La Tortura", "-")
   ,new SongObject("Shania Twain", "Man I Feel Like A Woman", "-")
   ,new SongObject("Shannon Noll", "What About Me", "-")
   ,new SongObject("Sia", "Chandelier", "-")
   ,new SongObject("Silbermond", "Irgendwas bleibt", "-")
   ,new SongObject("Sir Mix", "a-Lot - Baby Got Back", "-")
   ,new SongObject("Smashing Pumpkins", "Bullet with Butterfly Wings", "-")
   ,new SongObject("Smashing Pumpkins", "Cherub Rock", "-")
   ,new SongObject("Smashing Pumpkins", "Today", "-")
   ,new SongObject("Soda Stereo", "Cuando Pase el Temblor", "-")
   ,new SongObject("Soda Stereo", "Persiana Americana", "-")
   ,new SongObject("Spice Girls", "Say You'll Be There", "-")
   ,new SongObject("Steppenwolf", "Born to Be Wild", "-")
   ,new SongObject("Stone Temple Pilots", "Vasoline", "-")
   ,new SongObject("Sublime", "Santeria", "-")
   ,new SongObject("System Of A Down", "Aerials", "-")
   ,new SongObject("System of a Down", "BYOB", "-")
   ,new SongObject("System of a Down", "Chop Suey", "-")
   ,new SongObject("Tatu", "All The Things She Said", "-")
   ,new SongObject("The Beatles", "Twist and Shout", "-")
   ,new SongObject("The Pogues", "Dirty Old Town", "-")
   ,new SongObject("The Pogues feat. Kirsty MacColl", "Fairytale of New York", "-")
   ,new SongObject("Three Days Grace", "I Hate Everything About You", "-")
   ,new SongObject("Tina Turner & Ike", "Proud Mary", "-")
   ,new SongObject("Tina Turner", "Private Dancer", "-")
   ,new SongObject("Tom Jones", "Delilah", "-")
   ,new SongObject("Tom Jones", "It's Not Unusual", "-")
   ,new SongObject("Tom Jones", "Sexbomb", "-")
   ,new SongObject("Tom Jones", "What's New Pussycat", "-")
   ,new SongObject("Tool", "Sober", "-")
   ,new SongObject("Tove Lo", "Habits (Stay High)", "-")
   ,new SongObject("Tracy Chapman", "Baby Can I Hold You", "-")
   ,new SongObject("Tracy Chapman", "Fast Car", "-")
   ,new SongObject("Vicente Fernandez", "El Rey", "-")
   ,new SongObject("Vicente Fernandez", "Volver volver", "-")
   ,new SongObject("Vicente Fernández", "El último beso", "-")
   ,new SongObject("Vicente Fernández", "Estos celos", "-")
   ,new SongObject("Vicente Fernández", "Lástima que seas ajena", "-")
   ,new SongObject("Vicente Fernández", "Millón de primaveras", "-")
   ,new SongObject("Vicente Fernández", "Mujeres divinas", "-")
   ,new SongObject("Vicente Fernández", "Por tu maldito amor", "-")
   ,new SongObject("Vicente Fernández", "Que te vaya bonito", "-")
   ,new SongObject("Vicente Fernández", "Si te vas no hay lío", "-")
   ,new SongObject("Vicente Fernández y Alejandro Fernández", "Perdón", "-")
   ,new SongObject("Village People", "YMCA", "-")
   ,new SongObject("Weezer", "Say It Ain't So", "-")
  ]
};
